---
- name: Issue Junos RPC
  hosts: 192.168.0.101
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
    - name: USERNAME
      prompt: Username
      private: no
    - name: DEVICE_PASSWORD
      prompt: Password
      private: yes
    - name: IP
      prompt: IP
      private: no

  tasks:
  - name: Issue Junos RPC
    juniper_junos_rpc:
      user: "{{ USERNAME }}"
      passwd: "{{ DEVICE_PASSWORD }}"
      rpcs: get-arp-table-information
      args:
        hostname: "{{ IP }}"
    register: rpc_response

  - name: Print Junos facts
    debug:
      #msg: "{{ juniper_facts }}"
      var: rpc_response["parsed_output"]["arp-table-information"]['arp-table-entry']['interface-name']
